### ISSUE TITLE
Experiment idea: Using sveltosis 

### ISSUE THREAD

**Issue by bfanger** [bfanger/svelte-preprocess-react#15]
https://try.sveltosis.dev/ 
This tech allows generating react-component-code from Svelte files.

This could allow the preprocessor to add support for:

```ts
import { ReactComponent as Button } from "$lib/components/Button.svelte";
```

**Comment by jonathanstanley** [comment]
fyi the project is now incorporated into https://github.com/builderio/mitosis

**Comment by bfanger** [comment]
The primary goal of svelte-preprocess-react is to provide **compatibility**.

Using real Svelte components, compiled by the official svelte/compiler is favorable because it prevents inconsistenties.
https://mitosis.builder.io/docs/gotchas/
