### ISSUE TITLE
Binding issue

### ISSUE THREAD

**Issue by Kax675** [bfanger/svelte-preprocess-react#22]
I don't need to talk too much, the bindings don't work. Anyone know the solution for this?

![image](https://user-images.githubusercontent.com/93868975/216327532-0dc65df7-cf56-4a4a-afaf-15ab06beb6a1.png)
![image](https://user-images.githubusercontent.com/93868975/216327783-0d032d65-3511-484a-b86c-a6498db8c348.png)

**Comment by bfanger** [comment]
React doesn't have two-way data binding. 
Use the classic React way of updating the value using the `onChange`:

```svelte
<script lang="ts">
  import { Input, Text } from "@geist-ui/core";

  let value = "";
</script>

<react:Input {value} on:change={(e) => { value = e.target.value }} />
<react:Text>{value}</react:Text>
```
