### ISSUE TITLE
Is it possible to use it with React Native?

### ISSUE THREAD

**Issue by ozio** [bfanger/svelte-preprocess-react#23]
Or is it possible to implement this feature in the package's boundaries? I understand that this is a very rare case, so I'm not asking to implement it.

**Comment by bfanger** [comment]
No, it doesn't work. I'm using react-dom and DOM api's to mount the components.

Not sure if nativescript (which svelte-native  uses) play nice with react-native architecture.

Interesting question, but it's outside the current scope of this project.

You could look into using react-native-webview a react-native component that allows using any web framework.

**Comment by ozio** [comment]
OK, thank you!

I saw you using react-dom but didn't dive deep enough.
