### ISSUE TITLE
Void and Self-Closing elements?

### ISSUE THREAD

**Issue by Kax675** [bfanger/svelte-preprocess-react#25]
I'm trying to use NextUI with SvelteKit but turns out preprocessor tries to add children like void or self closing elements

![image](https://user-images.githubusercontent.com/93868975/234198164-70785665-e925-4d5c-96a3-92fbcd527191.png)

![image](https://user-images.githubusercontent.com/93868975/234197982-af411869-ee76-4ce1-95da-ad5d915440a9.png)

Is there any solution for that?

**Comment by bfanger** [comment]
Thanks for reporting! the issue is fixed in 0.15.0
