### ISSUE TITLE
Using this package in a sveltekit SPA(no server) causes a few errors

### ISSUE THREAD

**Issue by avivash** [bfanger/svelte-preprocess-react#26]
Hi, thanks for making this package, it's great!

I am seeing a couple issues in my sveltekit app when deploying it as an SPA though. 

The first issue is a `global is not defined` error, even though I have 
```js
define: {
  global: 'globalThis'
},
```
inside my `vite.config`:
<img width="534" alt="image" src="https://user-images.githubusercontent.com/1179291/236286108-b2a95320-2ac3-4305-93b0-b3654fe04c47.png">

If i then manually set `global = window` in my `app.html`, I get the following `require is not defined` error even though i have no `require`s in my code:
<img width="531" alt="image" src="https://user-images.githubusercontent.com/1179291/236285710-58da0c6b-3971-4e8d-b6b7-a41d8a11e81b.png">

Any help you can offer would be much appreciated, thanks!

**Comment by bfanger** [comment]
We dont use require either, im but sure the svelte-preprocess-react package is the culprit. 

Does the application build and run without errors if you dont use any of the react components?

**Comment by avivash** [comment]
@bfanger it looks like it was an issue with the react library i was using. the team who created it is going to work on launching a framework agnostic SDK, so I'll use that moving forward. Closing this for now. Thanks!
