### ISSUE TITLE
Svelte 4

### ISSUE THREAD

**Issue by cortopy** [bfanger/svelte-preprocess-react#27]
Are there any plans to support Svelte 4? Since the bundle size should be smaller with the latest version, it seems like it would fit nicely to the use case of this React wrapper.

**Comment by bfanger** [comment]
**Yes!**

Aside from some Typescript changes which will be fixed in v0.16, the current v0.15 is already compatible with Svelte 4.

PS. Bundle size is not high on the priority list for this project:
> Compatibility first, Ease-of-use second and Performance last.
> - docs/architecture.md
