### ISSUE TITLE
cannot find module 'react-dom/client'

### ISSUE THREAD

**Issue by ctwhome** [bfanger/svelte-preprocess-react#29]
Using the example: 
```
<script>
  import YouTube from "react-youtube";
</script>

<react:YouTube videoId="AdNJ3fydeao" />
```
it returns cannot find module 'react-dom/client'.
I am using sveltekit latest

**Comment by bfanger** [comment]
Did you install react-dom and if so which version?

**Comment by ctwhome** [comment]
you are right. also needed to install just react

**Comment by ctwhome** [comment]
I am trying to add excalidraw to sveltekit? did you have any success with it?
