### ISSUE TITLE
React context example/docs?

### ISSUE THREAD

**Issue by gigamesh** [bfanger/svelte-preprocess-react#35]
I'm trying to use a third-party authentication SDK but I'm unsure how to implement svelte-preprocess-react to use it in my svelte app. Are there any examples or documentation somewhere?

**Comment by bfanger** [comment]
The react-router example [+layout.svelte](https://github.com/bfanger/svelte-preprocess-react/blob/main/src/routes/react-router/%2Blayout.svelte) & [+page.svelte](https://github.com/bfanger/svelte-preprocess-react/blob/main/src/routes/react-router/%5Bslug%5D/%2Bpage.svelte) is an example of using React context.

To read the context you can use the [hooks](https://github.com/bfanger/svelte-preprocess-react/blob/main/docs/hooks.md)

```svelte
<script lang="ts">
import { useUser }  from "third-party-auth"

const user = hooks(() => useUser())

$: console.log($user)
</script>
```

**Comment by gigamesh** [comment]
awesome thank you!
