### ISSUE TITLE
React Component Causing Svelte 505 Errors

### ISSUE THREAD

**Issue by Jholder7** [bfanger/svelte-preprocess-react#37]
Attempting to use the example as given in the read-me I keep getting: 

Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object.
Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.

Any suggestions on hoe to begin to debug this issue?

**Comment by bfanger** [comment]
When you write `<react:Thing>` make sure that _Thing_ is imported and a React component.
The error describes that what you passed as _Thing_ is an object instead of a component.
