### ISSUE TITLE
How to: convert react component with multiple properties

### ISSUE THREAD

**Issue by zeskysee** [bfanger/svelte-preprocess-react#38]
I had an app layout that look like this, may I know how to convert it to a svelte component so i could passed in the primary header, sidebar & main which is also a sveltify component?

```
<AppLayout
  header={
    <PrimaryHeader productName="name" />
  }
  sidebar={
    <Sidebar
      open={sidebarOpen}
      onToggle={setSidebarOpen}
      openContent={<div style={{ width: spacing192 }} />}
    />
  }
  main={<Outlet />}
/>
```

**Comment by bfanger** [comment]
In pure Svelte you'd use named slots. 
(And in Svelte 5 you'd use snippets)

But this not (yet?) supported by sveltified components.

You can pass React elements as props, but you can't use jsx inside a svelte file, but you can write:

'''
<AppLayout header={createElement(Header, {title: "a prop"})}

**Comment by zeskysee** [comment]
Thank you for your quick response
