### ISSUE TITLE
Trouble Installing 2.0.0-beta.6 with Svelte 5

### ISSUE THREAD

**Issue by ddxv** [bfanger/svelte-preprocess-react#41]
`npm install svelte-preprocess-react@beta`
```sh
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: kit-dash@0.0.1
npm ERR! Found: svelte@5.0.0-next.262
npm ERR! node_modules/svelte
npm ERR!   dev svelte@"^5.0.0-next.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer svelte@">=5.0.0" from svelte-preprocess-react@2.0.0-beta.6
npm ERR! node_modules/svelte-preprocess-react
npm ERR!   svelte-preprocess-react@"2.0.0-beta.6" from the root project
```

A bit odd, since `Found: svelte@5.0.0-next.262` vs `peer svelte@">=5.0.0" from svelte-preprocess-react@2.0.0-beta.6` don't seem to be in conflict. Apologies if this is basic, I'm new to js/svelte.

If I try to push past this with ` npm install svelte-preprocess-react@beta --legacy-peer-deps`

I got this error from `npm build`:
```
0.223 > kit-dash@0.0.1 build
0.223 > vite build
0.223 
0.834 error during build:
0.834 TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".svelte" for /apps/dash-frontend/node_modules/svelte-preprocess-react/dist/internal/SvelteWrapper.svelte
0.834     at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:176:9)
0.834     at defaultGetFormat (node:internal/modules/esm/get_format:219:36)
0.834     at defaultLoad (node:internal/modules/esm/load:143:22)
0.834     at async ModuleLoader.load (node:internal/modules/esm/loader:555:7)
0.834     at async ModuleLoader.moduleProvider (node:internal/modules/esm/loader:434:45) 
```

**Comment by bfanger** [comment]
The next release will change the peerDependency from `"svelte@">=5.0.0"` to `"svelte@">=5.0.0-beta"` to also include the svelte preleases. 
I use pnpm which has as i learned today has less strict semver checking compared to npm, so thanks for reporting!

The  `Unknown file extension ".svelte"` error however is unrelated, it seems you haven't set up your bundler to process svelte files.
Open your vite configuration and check if the svelte or sveltekit vite plugins are configured correctly. See https://github.com/sveltejs/vite-plugin-svelte for details

**Comment by ddxv** [comment]
> The next release will change the peerDependency from `"svelte@">=5.0.0"` to `"svelte@">=5.0.0-beta"` to also include the svelte preleases. I use pnpm which has as i learned today has less strict semver checking compared to npm, so thanks for reporting!
> 
> The `Unknown file extension ".svelte"` error however is unrelated, it seems you haven't set up your bundler to process svelte files. Open your vite configuration and check if the svelte or sveltekit vite plugins are configured correctly. See https://github.com/sveltejs/vite-plugin-svelte for details

Awesome news, will look forward to that. And yeah, I must have had a separate issue, the svelte went away after reverting back, so might have typoed when I made the edit there. 

Looking forward checking back in when the next version is out.

**Comment by andupotorac** [comment]
Looking forward to this also! I tried to install fro Svelte 5 and I get the same error.

**Comment by bfanger** [comment]
Both svelte 5 & svelte-preprocess-react 2 are now released.
