### ISSUE TITLE
The ReactDOMClient parameter is required for hooks

### ISSUE THREAD

**Issue by devcsrj** [bfanger/svelte-preprocess-react#45]
### Context

I have a **svelte 4** app, so I installed `svelte-preprocess-react@1.0.0`. I am trying to embed [tldraw](https://github.com/tldraw/tldraw), and found this promising preprocessor.

### Reproducible build

[Stackblitz](https://stackblitz.com/edit/sveltejs-kit-template-default-d1r3cw?file=src%2Froutes%2F%2Bpage.svelte) or [Github repo](https://github.com/devcsrj/bug-reports/tree/master/svelte-preprocess-react-45)

Renders the  component nicely. However, if `useEditor` is uncommented:

```
  // const editor = hooks(() => useEditor());
  // console.log('editor', editor)
```

The following stacktrace will show in the console:

```
svelte-preprocess-react.js?v=c2551f75:82 Uncaught (in promise) Error: The ReactDOMClient parameter is required for hooks(), because no parent component was a sveltified React component
    at hooks (svelte-preprocess-react.js?v=c2551f75:82:11)
    at instance (+page.svelte:6:3)
    at init (chunk-3XBAGWFC.js?v=c2551f75:2139:23)
    at new Page (+page.svelte:7:3)
    at createProxiedComponent (svelte-hooks.js?v=c2551f75:341:9)
    at new ProxyComponent (proxy.js?v=c2551f75:242:7)
    at new Proxy<+page> (proxy.js?v=c2551f75:349:11)
    at construct_svelte_component_dev (chunk-3XBAGWFC.js?v=c2551f75:2571:22)
    at Array.create_default_slot (root.svelte:47:86)
    at create_slot (chunk-3XBAGWFC.js?v=c2551f75:99:25)
```

**Comment by bfanger** [comment]
If a Svelte component is wrapped in a React component like a provider, then `hooks()` has access to the injected React libraries. It is possible to use a hooks without a wrapper, but then you'll have to provide the libraries manually:

```ts
import ReactDOMClient from "react-dom/client"; // React 18
// import ReactDOMClient from "react-dom"; // React 16 or 17
import { renderToString } from "react-dom/server";
  
const editor = hooks(() => useEditor(), ReactDOMClient, renderToString)
```
( renderToString is only needed when the component is also server rendered )

I'll look into if the preprocessor can inject these dependencies automatically  when it sees a `hooks()` call, but that will probably be a 2.x feature.

**Comment by devcsrj** [comment]
Oh, that works! 

Interestingly enough, I tried that before but was getting a different error. Apparently it's from the [tldraw library](https://github.com/tldraw/tldraw/blob/dada4a23b757a91567e9ec641a7845f5c47144d8/packages/editor/src/lib/hooks/useEditor.tsx#L12C1-L14C4).

Thank you @bfanger !
